-- MySQL Script generated by MySQL Workbench
-- Sun Feb  9 18:11:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stockdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stockdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stockdb` DEFAULT CHARACTER SET utf8 ;
USE `stockdb` ;

-- -----------------------------------------------------
-- Table `stockdb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockdb`.`Users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(15) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockdb`.`Wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockdb`.`Wallet` (
  `id_wallet` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `quantidade_acoes` INT NOT NULL,
  PRIMARY KEY (`id_wallet`),
  INDEX `fk_Wallet_Users1_idx` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_Wallet_Users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `stockdb`.`Users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockdb`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockdb`.`Company` (
  `id_company` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NULL,
  UNIQUE INDEX `company_name_UNIQUE` (`company_name` ASC) VISIBLE,
  PRIMARY KEY (`id_company`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockdb`.`Stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockdb`.`Stocks` (
  `id_stock` INT NOT NULL AUTO_INCREMENT,
  `id_company` INT NOT NULL,
  `ticker` VARCHAR(15) NULL,
  UNIQUE INDEX `ticker_UNIQUE` (`ticker` ASC) VISIBLE,
  PRIMARY KEY (`id_stock`),
  INDEX `fk_Stocks_Company1_idx` (`id_company` ASC) VISIBLE,
  UNIQUE INDEX `id_company_UNIQUE` (`id_company` ASC) VISIBLE,
  CONSTRAINT `fk_Stocks_Company1`
    FOREIGN KEY (`id_company`)
    REFERENCES `stockdb`.`Company` (`id_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stockdb`.`Wallet_has_Stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stockdb`.`Wallet_has_Stocks` (
  `id_wallet` INT NOT NULL,
  `id_stock` INT NOT NULL,
  `max_price` DECIMAL(5,2) NULL,
  `min_price` DECIMAL(5,2) NULL,
  `periodo_visualizacao` INT NULL,
  PRIMARY KEY (`id_wallet`, `id_stock`),
  INDEX `fk_Wallet_has_Stocks_Stocks1_idx` (`id_stock` ASC) VISIBLE,
  INDEX `fk_Wallet_has_Stocks_Wallet1_idx` (`id_wallet` ASC) VISIBLE,
  CONSTRAINT `fk_Wallet_has_Stocks_Wallet1`
    FOREIGN KEY (`id_wallet`)
    REFERENCES `stockdb`.`Wallet` (`id_wallet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Wallet_has_Stocks_Stocks1`
    FOREIGN KEY (`id_stock`)
    REFERENCES `stockdb`.`Stocks` (`id_stock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
